export const nigerianBanks = [
  { name: 'Access Bank', code: '044' },
  { name: 'GTBank', code: '058' },
  { name: 'First Bank of Nigeria', code: '011' },
  { name: 'Zenith Bank', code: '057' },
  { name: 'United Bank for Africa (UBA)', code: '033' },
  { name: 'Fidelity Bank', code: '070' },
  { name: 'Union Bank', code: '032' },
  { name: 'Stanbic IBTC Bank', code: '221' },
  { name: 'Sterling Bank', code: '232' },
  { name: 'Wema Bank', code: '035' },
  { name: 'Polaris Bank', code: '076' },
  { name: 'Ecobank Nigeria', code: '050' },
  { name: 'Keystone Bank', code: '082' },
  { name: 'FCMB', code: '214' },
  { name: 'Heritage Bank', code: '030' },
  { name: 'Unity Bank', code: '215' },
  { name: 'Providus Bank', code: '101' },
  { name: 'Jaiz Bank', code: '301' },
  { name: 'Citibank Nigeria', code: '023' },
  { name: 'Standard Chartered Bank', code: '068' },
  { name: 'Kuda Bank', code: '50211' },
  { name: 'VFD Microfinance Bank', code: '566' },
  { name: 'Rubies Bank', code: '125' },
  { name: 'Titan Trust Bank', code: '102' },
  { name: 'Globus Bank', code: '00103' },
  { name: 'Parallex Bank', code: '526' },
  { name: 'SunTrust Bank', code: '100' },
  { name: 'Optimus Bank', code: '107' }
];
