"use client";

import { useEffect } from "react";

/**
 * Component to register the push service worker early in the app lifecycle.
 * This ensures the push-sw.js is registered separately from the main sw.js
 * generated by next-pwa.
 */
export default function PushSWRegistration() {
	useEffect(() => {
		if ("serviceWorker" in navigator) {
			// Register push service worker
			navigator.serviceWorker
				.register("/push-sw.js", { scope: "/" })
				.then((registration) => {
					console.log(
						"[Push SW] Service worker registered successfully:",
						registration
					);
				})
				.catch((error) => {
					console.error("[Push SW] Service worker registration failed:", error);
				});
		}
	}, []);

	return null; // This component doesn't render anything
}
